### ISSUE TITLE
Error in tuyapi

### ISSUE THREAD

**Issue by minscof** [vinodsr/node-red-contrib-tuya-smart-device#143]
I have 4 tuya bulbs.

When I active theses bulbs, nodered fails and stops.

I have this message in the log :

[error] TypeError: Cannot read properties of undefined (reading 'payload')
2024-03-23T17:14:38.587789678Z     at Socket.<anonymous> (/data/node_modules/tuyapi/index.js:985:30)
2024-03-23T17:14:38.587806419Z     at Socket.emit (node:events:513:28)
2024-03-23T17:14:38.587819678Z     at UDP.onMessage [as onmessage] (node:dgram:930:8)

I use the version 5.2 of the node.

Can you help ?
Thank you

**Comment by Eucliwood090** [comment]
i have the same probleme, an idea ?

**Comment by iainmc83** [comment]
I have the same issue. In the version of tuyapi that this repo uses, the problem is caused by a prefix error that I managed to surface.

```
TypeError: Prefix does not match: 0000669900000000000000000013000000ef18e50e3166d903b212dcf474d350b9a60368c20de852a60f097eb08cd2cebfc4be6b061d7fc95d05354ad9b981024152cdce6119eb5df16718edc92aab320bf14af2c184d11c7d1ec1b54de7e21c34830a65e71af2332474f5c280bc4e7962288228df3bc8f71aba9c24739310477bee094becd986db3eb01a5cfc33b25150c8a2e3928443591e5a678aa04021bc8c3a89a2e2868a65c6c81bb28c24e41900f21dff928125dbf50c0a1a3e2ca21c87825d45e13c9911905dae6b039b3d147e228fd660d78829fa481ac5efba580b557653080d8fad6bd094499092f13c8296f3341d333141006fc4d77c611a12306400009966
    at MessageParser.parsePacket (/home/iain/.node-red/node_modules/tuyapi/lib/message-parser.js:113:13)
    at MessageParser.parseRecursive (/home/iain/.node-red/node_modules/tuyapi/lib/message-parser.js:238:25)
    at MessageParser.parse (/home/iain/.node-red/node_modules/tuyapi/lib/message-parser.js:259:17)
    at Socket.<anonymous> (/home/iain/.node-red/node_modules/tuyapi/index.js:976:26)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at UDP.onMessage [as onmessage] (node:dgram:942:8)
```

This particular issue is fixed in the latest version of tuyapi and the new prefix is handled: https://github.com/codetheweb/tuyapi/blob/master/lib/message-parser.js#L114-L116

_However_ - a further error is thrown when tuyapi tries to process the data from these devices. I have raised an issue over there which will need to be fixed before dependencies are updated here. https://github.com/codetheweb/tuyapi/issues/676

Happy to help where I can - but I lack the development chops to be able to figure this one out by myself.
