### ISSUE TITLE
Node not works if some characters in the key

### ISSUE THREAD

**Issue by mrmaximas** [vinodsr/node-red-contrib-tuya-smart-device#146]
I use the latest version 5.3.0 of this node.
Many of my devices already have alphanumeric keys
Node does not connect to the device if some characters in the key, for example:
working key - J0;7-Br<[<zFqMmP
working key - uGX'P>Fg5g]b!Gu9
working key - ;6;<5`szz7]IyT@S
bad key - .74<{0I}Z*zm$jMa
bad key - ut^m/z[GA1A<{E?]
I think { or } symbols is a problem.
How to fix it?
Thanks!

**Comment by vinodsr** [comment]
Is it possible for you to share the logs

**Comment by mrmaximas** [comment]
> Is it possible for you to share the logs

21/06/2024, 20:15:41[node: Kitchen](http://192.168.xx.xx:1880/#)
msg : string[61]
"Error from tuyaDevice. shouldTryReconnect = true, error  = {}"
21/06/2024, 20:15:51[node: Kitchen](http://192.168.xx.xx:1880/#)
msg : string[61]
"Error from tuyaDevice. shouldTryReconnect = true, error  = {}"
21/06/2024, 20:16:01[node: Kitchen](http://192.168.xx.xx:1880/#)
msg : string[61]
"Error from tuyaDevice. shouldTryReconnect = true, error  = {}"
21/06/2024, 20:16:11[node: Kitchen](http://192.168.xx.xx:1880/#)
msg : string[61]
"Error from tuyaDevice. shouldTryReconnect = true, error  = {}"

**Comment by mrmaximas** [comment]
> Is it possible for you to share the logs


21 Jun 20:43:22 - [info] [tuya-smart-device:Home Kitchen Boiler] startComm(): Connecting to Tuya
21 Jun 20:43:22 - [info] [tuya-smart-device:Home Kitchen Boiler] findDevice(): Initiating the find command
21 Jun 20:43:22 - [info] [tuya-smart-device:Home Kitchen Boiler] findDevice(): Found device, going to connect
21 Jun 20:43:23 - [info] [tuya-smart-device:Home Kitchen Boiler] Connected to device! name : Home Kitchen Boiler, ip : 192.168.1.193
21 Jun 20:43:24 - [error] [tuya-smart-device:Home Kitchen Boiler] Error from tuyaDevice. shouldTryReconnect = true, error  = {}
21 Jun 20:43:24 - [info] [tuya-smart-device:Home Kitchen Boiler] Disconnected from tuyaDevice. shouldTryReconnect = true
21 Jun 20:43:34 - [info] [tuya-smart-device:Home Kitchen Boiler] Retrying connection...
21 Jun 20:43:34 - [info] [tuya-smart-device:Home Kitchen Boiler] Connected to device! name : Home Kitchen Boiler, ip : 192.168.1.193
21 Jun 20:43:34 - [error] [tuya-smart-device:Home Kitchen Boiler] Error from tuyaDevice. shouldTryReconnect = true, error  = {}
21 Jun 20:43:34 - [info] [tuya-smart-device:Home Kitchen Boiler] Disconnected from tuyaDevice. shouldTryReconnect = true
21 Jun 20:43:43 - [error] [json:d2ffc2c8.f52098] Unexpected token '<', "<!DOCTYPE "... is not valid JSON
21 Jun 20:43:44 - [info] [tuya-smart-device:Home Kitchen Boiler] Retrying connection...
21 Jun 20:43:44 - [info] [tuya-smart-device:Home Kitchen Boiler] Connected to device! name : Home Kitchen Boiler, ip : 192.168.1.193
21 Jun 20:43:44 - [error] [tuya-smart-device:Home Kitchen Boiler] Error from tuyaDevice. shouldTryReconnect = true, error  = {}
21 Jun 20:43:44 - [info] [tuya-smart-device:Home Kitchen Boiler] Disconnected from tuyaDevice. shouldTryReconnect = true

**Comment by vinodsr** [comment]
are you able to communicate to the device using tuya-cli ? 

eg : tuya-cli get --id <deviceid> --key <device key>

**Comment by mrmaximas** [comment]
> are you able to communicate to the device using tuya-cli ?
> 
> eg : tuya-cli get --id --key

 ~ % tuya-cli get --ip 192.168.1.193 --id XXXXXXX --key .74<{0I}Z*zm$jMx
zsh: no matches found: {0I}Z*zm

**Comment by mrmaximas** [comment]
> are you able to communicate to the device using tuya-cli ?
> 
> eg : tuya-cli get --id --key

~ % tuya-cli get --ip 192.168.1.193 --id XXXXXXX --key .74<{0I}Zzm$jMa
zsh: no matches found: {0I}Zzm

**Comment by vinodsr** [comment]
try this 

tuya-cli get --ip 192.168.1.193 --id XXXXXXX --key ".74<{0I}Zzm$jMa"

**Comment by mrmaximas** [comment]
> try this
> 
> tuya-cli get --ip 192.168.1.193 --id XXXXXXX --key ".74<{0I}Zzm$jMa"

/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:78
      throw new TypeError('Key is missing or incorrect.');
            ^

**Comment by mrmaximas** [comment]
> try this
> 
> tuya-cli get --ip 192.168.1.193 --id XXXXXXX --key ".74<{0I}Zzm$jMa"

tuya-cli get --ip 192.168.1.193 --id xxxxxxx --key ".74<{0I}Z*zm$jMa"
/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:78
      throw new TypeError('Key is missing or incorrect.');
            ^

TypeError: Key is missing or incorrect.
    at new TuyaDevice (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:78:13)
    at parseConfig (/opt/homebrew/lib/node_modules/@tuyapi/cli/lib/control.js:32:9)
    at Object.get (/opt/homebrew/lib/node_modules/@tuyapi/cli/lib/control.js:36:15)
    at Command.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/cli.js:63:11)
    at Command.listener [as _actionHandler] (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:882:12)
    at Command.parse (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/cli.js:134:9)

**Comment by mrmaximas** [comment]
herewith

tuya-cli get --ip 192.168.1.191 --id YYYYYYY --key "ut^m/z[GA1A<{E?]"
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:651:26)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on TuyaDevice instance at:
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:651:12)
    at Socket.emit (node:events:519:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by mrmaximas** [comment]
herewith

tuya-cli get --ip 192.168.1.191 --id YYYYYYY --key ut^m/z[GA1A<{E?]
zsh: bad pattern: ut^m/z[GA1A

tuya-cli get --ip 192.168.1.191 --id YYYYYYY --key "ut^m/z[GA1A<{E?]"
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:651:26)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on TuyaDevice instance at:
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:651:12)
    at Socket.emit (node:events:519:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
